const SEED_PRODUCTS=[{"id": "514001", "name": "Smoking Gold King Size Slim 50 stk", "brand": "Smoking", "category": "Rullepapir", "price": 0, "stock": 0, "tag": "SM", "description": "King Size Slim rullepapir i displaypakke. Et ryddig premiumvalg for butikkens papirsortiment."}, {"id": "514002", "name": "Smoking Blue King Size Regular 50 stk", "brand": "Smoking", "category": "Rullepapir", "price": 0, "stock": 0, "tag": "SM", "description": "King Size Regular rullepapir med klassisk profil og praktisk displaypakning."}, {"id": "514960", "name": "Greengo Unbleached King Size Slim 50 stk", "brand": "Greengo", "category": "Rullepapir", "price": 0, "stock": 0, "tag": "GG", "description": "Ubleket King Size Slim papir fra Greengo i displaypakke."}];
const key="tb_products";
const $=id=>document.getElementById(id);
function getProducts(){return JSON.parse(localStorage.getItem(key)||JSON.stringify(SEED_PRODUCTS))}
function setProducts(list){localStorage.setItem(key,JSON.stringify(list));render()}
function message(text){$("message").textContent=text;$("message").classList.remove("hidden")}
function render(){const list=getProducts();$("admin-count").textContent=list.length;$("admin-products").innerHTML=list.map(p=>`<tr><td>${p.name}<br><span class="muted">${p.brand||""} / ${p.id}</span></td><td>${p.category}</td><td>${p.price||0}</td><td>${p.stock||0}</td><td><button class="btn danger" onclick="removeProduct('${p.id}')">Slett</button></td></tr>`).join("")}
function removeProduct(id){setProducts(getProducts().filter(p=>String(p.id)!==String(id)))}
$("product-form").addEventListener("submit",e=>{e.preventDefault();const item={id:$("id").value||Date.now().toString(),name:$("name").value,brand:$("brand").value,category:$("category").value,price:Number($("price").value||0),stock:Number($("stock").value||0),tag:$("tag").value||"TB",description:$("description").value};setProducts([item,...getProducts().filter(p=>String(p.id)!==String(item.id))]);e.target.reset();message("Produkt lagret.")})
$("csv-file").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const headers=lines.shift().split(",").map(x=>x.trim());const rows=lines.map(line=>{const values=line.split(",");const r=Object.fromEntries(headers.map((h,i)=>[h,(values[i]||"").trim()]));return {id:r.sku||r.id||Date.now().toString()+Math.random(),name:r.name||"",brand:r.brand||"",category:r.category||"Tilbehør",price:Number(r.price_nok||r.price||0),stock:Number(r.stock||0),tag:(r.brand||"TB").slice(0,2).toUpperCase(),description:r.description||r.desc||""}});setProducts([...rows,...getProducts()]);message(rows.length+" produkter importert.")})
$("export-json").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(getProducts(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="products.json";a.click()})
$("reset-products").addEventListener("click",()=>{setProducts(SEED_PRODUCTS);message("Startdata gjenopprettet.")})
render();
